//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class studentEntities1 : DbContext
    {
        public studentEntities1()
            : base("name=studentEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dbo_employee> dbo_employee { get; set; }
        public virtual DbSet<info> infoes { get; set; }
        public virtual DbSet<table3> table3 { get; set; }
        public virtual DbSet<employee_salary_details> employee_salary_details { get; set; }
    }
}
